### PR TITLE
fix two issues

### PR DESCRIPTION
**Pull request by shuxiao9058**
- csv parse issue `column 64: bare " in non-quoted-field`
- peer and item may contain quotes

### CODE REVIEW

**Comment by shuxiao9058** [comment]
And make posting after meta info.

**Comment by Triple-Z** [comment]
> And make posting after meta info.

Why the posting should place after the metadata?

**Comment by shuxiao9058** [comment]
Refered to the Python beancount parse module which put posting after metadata.

**Comment by Triple-Z** [comment]
SGTM, /cc @gaocegege

**Comment by Triple-Z** [comment]
I suggest that add an extra test for this "csv parse issue column 64: bare " in non-quoted-field"

**Review by Triple-Z — COMMENTED** [review]
I suggest that add an extra test for this "csv parse issue column 64: bare " in non-quoted-field"

**Comment by shuxiao9058** [comment]
> I suggest that add an extra test for this "csv parse issue column 64: bare " in non-quoted-field"

done with recent commit.

**Review by Triple-Z — APPROVED** [review]
LGTM.

**Comment by Triple-Z** [comment]
Maybe we can sync this fix to `alipay` provider too.

**Comment by shuxiao9058** [comment]
> Maybe we can sync this fix to `alipay` provider too.

done with commit https://github.com/deb-sig/double-entry-generator/pull/55/commits/c0d3a77f1dbd79cb0c35a2a6a9096b915cb74472

**Review by Triple-Z — APPROVED** [review]
LGTM

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Pull request merged**
