### PR TITLE
feat: support jd provider

### PR DESCRIPTION
**Pull request by CNLHC**
Support JD provider

### CODE REVIEW

**Review by Triple-Z — CHANGES_REQUESTED** [review]
Thanks for your contribution. 

Can you add tests for `jd` provider under the `tests` directory and run them by `Makefile`?

**Comment by CNLHC** [comment]
> Thanks for your contribution.
> 
> Can you add tests for `jd` provider under the `tests` directory and run them by `Makefile`?

sure

**Review by Triple-Z — APPROVED** [review]
LGTM

Please add README and describe how to export bills from JD if you are available.

**Review by Triple-Z — APPROVED** [review]

**Comment by Triple-Z** [comment]
Thanks for your contribution 🎉

**Pull request merged**
