### PR TITLE
fix the Type and TxType mapping error in the wechat provider

### PR DESCRIPTION
**Pull request by notzhan**
修复导入微信账单中，Type 和 TxType 的 convert 类型错误。

### CODE REVIEW

**Comment by Triple-Z** [comment]
Please fix the tests.

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

Please fix the test failures

**Comment by notzhan** [comment]
> Please fix the tests.

fixed.

**Review by gaocegege — APPROVED** [review]
LGTM :+1:
/lgtm

/cc @Triple-Z

**Comment by Triple-Z** [comment]
This is a historical problem for this project.

For the rules in YAML file, the `type` always stands for "income/expense", and `txType` stands for detailed transaction category.

However, for the implementation in `provider/*/types.go`, `provider/*/parse.go`, `analyser/*/*.go`, and `provider/*/convert.go` (like this case). the `type` and `txType` 's definition are different in these files, and easily get confused between them.

This PR is great, but I think we should unify the definition of `type` and `txType` in all phases. /cc @gaocegege

**Review by Triple-Z — APPROVED** [review]
LGTM

**Comment by gaocegege** [comment]
> This PR is great, but I think we should unify the definition of type and txType in all phases. /cc @gaocegege

SGTM, I think so.

**Comment by Triple-Z** [comment]
Thanks for your contribution 🎉

**Pull request merged**
